name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    name: deploy
    steps:
      - name: trigger-deploy
        env:
          TOKEN: ${{ secrets.OSEH_DEPLOYMENT_SECRET }}
        run: |
          curl -XPOST -H "Content-Type: application/json" https://oseh.io/api/1/continuous_deployment/update -d '{"repo":"websocket"}' -H "authorization: token $TOKEN"
